#!/bin/bash
local dir=$1
while read -d '' -r x; do
	local n="${x#${dir}}"
	n="${n#/}"
	local v=$(< "$x")
	if [[ -z "$v" ]]; then
		unset "$n"
	else
		eval "export $n=\$v"
	fi
done < <(find "${dir}" -type f -print0)

shift
exec "$@"
